[mysqld]
basedir=D:/dev/clm/runtime/tools/mysql-8.0.33-winx64
datadir=D:/dev/clm/runtime/data/mysql
port=3306
bind-address=127.0.0.1
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-storage-engine=INNODB
lower_case_table_names=1
max_allowed_packet=64M
innodb_buffer_pool_size=512M
sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
log-error=D:/dev/clm/runtime/logs/mysql-error.log
[client]
default-character-set=utf8mb4
