CREATE TABLE IF NOT EXISTS "clm_contract_type" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "description" varchar(512) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "sort" int NOT NULL DEFAULT 0,
    "current_version_id" bigint DEFAULT NULL,
    "template_file_key" varchar(255) DEFAULT NULL,
    "template_file_name" varchar(255) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同类型';

CREATE TABLE IF NOT EXISTS "clm_contract_type_version" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type_id" bigint NOT NULL,
    "version_no" int NOT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "form_conf" text,
    "form_fields" text,
    "process_definition_key" varchar(64) NOT NULL DEFAULT 'clm_contract_approval_v1',
    "remark" varchar(255) DEFAULT '',
    "published_time" timestamp DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同类型版本';

CREATE TABLE IF NOT EXISTS "clm_party" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "party_type" tinyint NOT NULL DEFAULT 1,
    "name" varchar(255) NOT NULL,
    "unified_credit_code" varchar(64) DEFAULT '',
    "internal_flag" bit NOT NULL DEFAULT FALSE,
    "contact_name" varchar(64) DEFAULT '',
    "contact_phone" varchar(32) DEFAULT '',
    "address" varchar(512) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "remark" varchar(255) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 签约方';

CREATE TABLE IF NOT EXISTS "clm_contract" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_no" varchar(64) DEFAULT NULL,
    "title" varchar(255) NOT NULL,
    "type_id" bigint NOT NULL,
    "type_version_id" bigint NOT NULL,
    "owner_user_id" bigint NOT NULL,
    "owner_dept_id" bigint DEFAULT NULL,
    "amount" decimal(18,2) DEFAULT NULL,
    "currency" varchar(8) NOT NULL DEFAULT 'CNY',
    "sign_date" date DEFAULT NULL,
    "effective_date" date DEFAULT NULL,
    "expiry_date" date DEFAULT NULL,
    "custom_data" text,
    "description" text,
    "lifecycle_status" tinyint NOT NULL DEFAULT 1,
    "approval_status" tinyint NOT NULL DEFAULT 0,
    "current_document_version_id" bigint DEFAULT NULL,
    "current_binding_id" bigint DEFAULT NULL,
    "source_contract_id" bigint DEFAULT NULL,
    "relation_type" varchar(32) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同';

CREATE TABLE IF NOT EXISTS "clm_contract_party" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_id" bigint NOT NULL,
    "party_id" bigint NOT NULL,
    "role_code" varchar(32) NOT NULL,
    "sort" int NOT NULL DEFAULT 0,
    "party_snapshot" text,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同签约方';

CREATE TABLE IF NOT EXISTS "clm_document" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_id" bigint NOT NULL,
    "role_code" varchar(32) NOT NULL DEFAULT 'MAIN',
    "name" varchar(255) NOT NULL,
    "current_version_id" bigint DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同文档';

CREATE TABLE IF NOT EXISTS "clm_document_version" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "document_id" bigint NOT NULL,
    "contract_id" bigint NOT NULL,
    "version_no" int NOT NULL,
    "parent_version_id" bigint DEFAULT NULL,
    "file_key" varchar(255) NOT NULL,
    "file_name" varchar(255) NOT NULL,
    "mime_type" varchar(128) DEFAULT '',
    "file_size" bigint NOT NULL DEFAULT 0,
    "checksum_sha256" char(64) NOT NULL,
    "source_type" varchar(32) NOT NULL DEFAULT 'UPLOAD',
    "frozen" bit NOT NULL DEFAULT FALSE,
    "remark" varchar(255) DEFAULT '',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 文档版本';

CREATE TABLE IF NOT EXISTS "clm_document_blob" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sha256" char(64) NOT NULL,
    "size" bigint NOT NULL,
    "content" longblob NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 文档内容';

CREATE TABLE IF NOT EXISTS "clm_workflow_binding" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_id" bigint NOT NULL,
    "purpose" varchar(32) NOT NULL DEFAULT 'APPROVAL',
    "process_definition_key" varchar(64) NOT NULL,
    "process_definition_id" varchar(64) DEFAULT '',
    "process_instance_id" varchar(64) DEFAULT NULL,
    "document_version_id" bigint NOT NULL,
    "contract_type_version_id" bigint NOT NULL,
    "form_snapshot" text,
    "checksum_sha256" char(64) NOT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "result_reason" varchar(512) DEFAULT '',
    "finished_time" timestamp DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 流程绑定';

CREATE TABLE IF NOT EXISTS "clm_contract_participant" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contract_id" bigint NOT NULL,
    "principal_type" varchar(16) NOT NULL DEFAULT 'USER',
    "principal_id" bigint NOT NULL,
    "role_code" varchar(32) NOT NULL,
    "can_view" bit NOT NULL DEFAULT TRUE,
    "can_edit" bit NOT NULL DEFAULT FALSE,
    "can_download" bit NOT NULL DEFAULT FALSE,
    "can_manage" bit NOT NULL DEFAULT FALSE,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 合同参与人';

CREATE TABLE IF NOT EXISTS "clm_audit_event" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "aggregate_type" varchar(32) NOT NULL,
    "aggregate_id" bigint NOT NULL,
    "contract_id" bigint DEFAULT NULL,
    "action" varchar(64) NOT NULL,
    "actor_user_id" bigint DEFAULT NULL,
    "actor_name" varchar(64) DEFAULT '',
    "detail_json" text,
    "occurred_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'CLM 审计事件';
