# Seed realistic demo data for the TuriX CLM demo (spec: docs/CLM_DEMO_SPEC.md section 3).
# Requires: backend with the demo endpoints (/clm/contract/copy, /clm/contract/archive,
#           /clm/contract-type/template/upload) deployed on 127.0.0.1:48080,
#           DOCX files generated by scripts/gen_demo_docs.py in runtime/demo-docs,
#           MySQL reachable via runtime/tools mysql.exe (password from infra/.env).
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File D:\dev\clm\scripts\seed-demo-data.ps1
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.Encoding]::UTF8
$Base = 'http://127.0.0.1:48080/admin-api'
$ClmRoot = 'D:\dev\clm'
$DocDir = Join-Path $ClmRoot 'runtime\demo-docs'
$script:Failures = 0

function Step($cond, $msg) {
  if ($cond) { Write-Host "  PASS  $msg" -ForegroundColor Green }
  else { Write-Host "  FAIL  $msg" -ForegroundColor Red; $script:Failures++ }
}
function Warn($msg) { Write-Host "  WARN  $msg" -ForegroundColor Yellow }
function Login($username, $password) {
  $body = [Text.Encoding]::UTF8.GetBytes((@{ username = $username; password = $password; tenantName = '芋道源码' } | ConvertTo-Json -Compress))
  $r = Invoke-WebRequest -Uri "$Base/system/auth/login" -Method POST -ContentType 'application/json;charset=UTF-8' -Headers @{ 'tenant-id' = '1' } -Body $body -UseBasicParsing
  $j = $r.Content | ConvertFrom-Json
  if ($j.code -ne 0) { throw "login failed for $username : $($j.msg)" }
  return @{ Authorization = "Bearer $($j.data.accessToken)"; 'tenant-id' = '1' }
}
function Api($headers, $method, $path, $data) {
  $params = @{ Uri = "$Base$path"; Method = $method; Headers = $headers; UseBasicParsing = $true }
  if ($null -ne $data) {
    $params.ContentType = 'application/json;charset=UTF-8'
    $params.Body = [Text.Encoding]::UTF8.GetBytes(($data | ConvertTo-Json -Compress -Depth 10))
  }
  try { $r = Invoke-WebRequest @params } catch { $r = $_.Exception.Response; if ($null -eq $r) { throw }; $sr = New-Object IO.StreamReader($r.GetResponseStream()); $txt = $sr.ReadToEnd(); return ($txt | ConvertFrom-Json) }
  return ($r.Content | ConvertFrom-Json)
}
function Upload($headers, $path, $fields, $filePath, $fileField = 'file') {
  $boundary = [Guid]::NewGuid().ToString()
  $LF = "`r`n"
  $ms = New-Object IO.MemoryStream
  $enc = [Text.Encoding]::UTF8
  foreach ($k in $fields.Keys) {
    $part = "--$boundary$LF" + "Content-Disposition: form-data; name=`"$k`"$LF$LF" + "$($fields[$k])$LF"
    $b = $enc.GetBytes($part); $ms.Write($b, 0, $b.Length)
  }
  $fileName = [IO.Path]::GetFileName($filePath)
  $head = "--$boundary$LF" + "Content-Disposition: form-data; name=`"$fileField`"; filename=`"$fileName`"$LF" + "Content-Type: application/octet-stream$LF$LF"
  $b = $enc.GetBytes($head); $ms.Write($b, 0, $b.Length)
  $fb = [IO.File]::ReadAllBytes($filePath); $ms.Write($fb, 0, $fb.Length)
  $tail = "$LF--$boundary--$LF"; $b = $enc.GetBytes($tail); $ms.Write($b, 0, $b.Length)
  $r = Invoke-WebRequest -Uri "$Base$path" -Method POST -Headers $headers -ContentType "multipart/form-data; boundary=$boundary" -Body $ms.ToArray() -UseBasicParsing
  return ($r.Content | ConvertFrom-Json)
}
function Merge($base, $extra) { $h = @{}; foreach ($k in $base.Keys) { $h[$k] = $base[$k] }; foreach ($k in $extra.Keys) { $h[$k] = $extra[$k] }; return $h }

# id trackers for the closing backdate SQL (only rows created by THIS run get touched)
$script:CreatedContractIds = @()   # list of @{ id = ...; offsetDays = ... }
$script:CreatedTypeIds = @()
$script:CreatedPartyIds = @()

try {

# ---------------------------------------------------------------- 0. logins
Write-Host "== step 0: logins + password resets"
$admin = Login 'admin' 'admin123'                      # user 1  (approval node2)
foreach ($uid in 100, 104, 114) {
  $r = Api $admin PUT '/system/user/update-password' @{ id = $uid; password = 'admin123' }
  Step ($r.code -eq 0) "password reset user id=$uid (msg=$($r.msg))"
}
$yudao = Login 'yudao' 'admin123'                      # user 100 (approval node1, 法务)
Step ($admin -and $yudao) 'admin + yudao logged in'

# ------------------------------------------------- 1. nickname touch-up (§3.2)
Write-Host "== step 1: user nickname touch-up (best effort)"
$nickMap = @(
  @{ id = 100; username = 'yudao'; nickname = '李静' },
  @{ id = 114; username = 'hrmgr'; nickname = '王慧' },
  @{ id = 104; username = 'test';  nickname = '赵晓敏' }
)
foreach ($n in $nickMap) {
  try {
    $u = (Api $admin GET "/system/user/get?id=$($n.id)").data
    if ($null -eq $u -or $u.username -ne $n.username) { Warn "user id=$($n.id) is not '$($n.username)' - skipped"; continue }
    $u.nickname = $n.nickname
    $r = Api $admin PUT '/system/user/update' $u
    if ($r.code -eq 0) { Step $true "nickname: $($n.username) -> $($n.nickname)" }
    else { Warn "nickname update for $($n.username) skipped (msg=$($r.msg))" }
  } catch { Warn "nickname update for $($n.username) failed: $($_.Exception.Message)" }
}

# ---------------------------------------------- 2. contract types + templates (§3.3)
Write-Host "== step 2: contract types (6) + field schemas + publish + template upload"
$dateStamp = Get-Date -Format 'yyyyMMdd'
# form-create rules: same shape as e2e-api.ps1 (JSON string per field)
$TypeSpecs = @(
  @{ key = 'purchase'; code = 'purchase'; name = '采购合同'; desc = '货物与设备采购类合同'; template = '采购合同范本.docx'; fields = @(
      '{"type":"datePicker","field":"deliveryDate","title":"交付日期","$required":true,"props":{"type":"date","valueFormat":"yyyy-MM-dd"},"_fc_id":"id_pu1","name":"ref_pu1","_fc_drag_tag":"datePicker","hidden":false,"display":true}',
      '{"type":"input","field":"acceptCriteria","title":"验收标准","props":{"type":"textarea"},"_fc_id":"id_pu2","name":"ref_pu2","_fc_drag_tag":"input","hidden":false,"display":true}',
      '{"type":"inputNumber","field":"warrantyMonths","title":"质保期月数","props":{},"_fc_id":"id_pu3","name":"ref_pu3","_fc_drag_tag":"inputNumber","hidden":false,"display":true}') },
  @{ key = 'sales'; code = 'sales'; name = '销售合同'; desc = '产品与服务对外销售类合同'; template = '销售合同范本.docx'; fields = @(
      '{"type":"inputNumber","field":"paymentDays","title":"回款账期天数","props":{},"_fc_id":"id_sa1","name":"ref_sa1","_fc_drag_tag":"inputNumber","hidden":false,"display":true}',
      '{"type":"switch","field":"freightIncluded","title":"是否含运费","props":{},"_fc_id":"id_sa2","name":"ref_sa2","_fc_drag_tag":"switch","hidden":false,"display":true}') },
  @{ key = 'tech-service'; code = 'tech-service'; name = '技术服务合同'; desc = '技术开发、运维与咨询服务合同'; template = '技术服务合同范本.docx'; fields = @(
      '{"type":"input","field":"servicePeriod","title":"服务周期","props":{},"_fc_id":"id_te1","name":"ref_te1","_fc_drag_tag":"input","hidden":false,"display":true}',
      '{"type":"input","field":"milestones","title":"验收里程碑","props":{"type":"textarea"},"_fc_id":"id_te2","name":"ref_te2","_fc_drag_tag":"input","hidden":false,"display":true}') },
  @{ key = 'lease'; code = 'lease'; name = '房屋租赁合同'; desc = '办公与仓储场地租赁合同'; template = '房屋租赁合同范本.docx'; fields = @(
      '{"type":"inputNumber","field":"leaseMonths","title":"租期月数","props":{},"_fc_id":"id_le1","name":"ref_le1","_fc_drag_tag":"inputNumber","hidden":false,"display":true}',
      '{"type":"inputNumber","field":"depositAmount","title":"押金(元)","props":{},"_fc_id":"id_le2","name":"ref_le2","_fc_drag_tag":"inputNumber","hidden":false,"display":true}') },
  @{ key = 'outsourcing'; code = 'outsourcing'; name = '劳务外包合同'; desc = '辅助业务劳务外包合同'; template = '劳务外包合同范本.docx'; fields = @(
      '{"type":"input","field":"settlementMethod","title":"结算方式","props":{},"_fc_id":"id_ou1","name":"ref_ou1","_fc_drag_tag":"input","hidden":false,"display":true}') },
  @{ key = 'nda'; code = 'nda'; name = '保密协议'; desc = '商务合作保密协议'; template = '保密协议范本.docx'; fields = @(
      '{"type":"inputNumber","field":"confidentialYears","title":"保密期限(年)","props":{},"_fc_id":"id_nd1","name":"ref_nd1","_fc_drag_tag":"inputNumber","hidden":false,"display":true}') }
)
$TypeIds = @{}
$sort = 0
foreach ($t in $TypeSpecs) {
  $sort++
  $body = @{ code = $t.code; name = $t.name; description = $t.desc; status = 0; sort = $sort; processDefinitionKey = 'clm_contract_approval_v1' }
  $r = Api $admin POST '/clm/contract-type/create' $body
  if ($r.code -ne 0) {
    # bare code already exists (re-run): retry with a date-stamp suffix
    Warn "type code '$($t.code)' exists, retrying as '$($t.code)-$dateStamp'"
    $body.code = "$($t.code)-$dateStamp"
    $r = Api $admin POST '/clm/contract-type/create' $body
  }
  if ($r.code -ne 0) { Step $false "type $($t.name) create (msg=$($r.msg))"; throw "type create failed" }
  $typeId = $r.data
  $TypeIds[$t.key] = $typeId
  $script:CreatedTypeIds += $typeId
  $draft = ((Api $admin GET "/clm/contract-type/version/list?typeId=$typeId").data | Where-Object { $_.status -eq 0 } | Select-Object -First 1)
  $r = Api $admin PUT '/clm/contract-type/version/update' @{ id = $draft.id; formConf = '{"form":{"labelWidth":"120px"}}'; formFields = $t.fields; processDefinitionKey = 'clm_contract_approval_v1'; remark = 'v1' }
  $r2 = Api $admin POST "/clm/contract-type/version/publish?id=$($draft.id)"
  Step ($r.code -eq 0 -and $r2.code -eq 0) "type $($t.name) id=$typeId schema saved + v1 published"
  $tpl = Upload $admin '/clm/contract-type/template/upload' @{ typeId = $typeId } (Join-Path $DocDir $t.template)
  Step ($tpl.code -eq 0) "type $($t.name) template uploaded: $($t.template) (msg=$($tpl.msg))"
}

# ---------------------------------------------------------- 3. parties (§3.4)
Write-Host "== step 3: parties (2 internal + 10 counterparties)"
$PartySpecs = @(
  @{ key = 'lx';   name = '灵犀科技（杭州）有限公司';       code = '91330106MA2GD3XT8B'; internal = $true;  contact = '沈亦凡'; phone = '0571-88215566' },
  @{ key = 'lxri'; name = '灵犀数智研究院';                 code = '52330000MJD1683544'; internal = $true;  contact = '顾若彤'; phone = '0571-88215588' },
  @{ key = 'hnyc'; name = '华南云创信息技术有限公司';       code = '91440300MA5FYK2D07'; internal = $false; contact = '陈立群'; phone = '0755-26013322' },
  @{ key = 'qmzz'; name = '启明智造设备股份有限公司';       code = '91320500MA1WChT29X'; internal = $false; contact = '宋建国'; phone = '0512-67885511' },
  @{ key = 'lwjs'; name = '蓝湾建设工程集团';               code = '91350200MA31HJ6C2E'; internal = $false; contact = '郑海峰'; phone = '0592-5033218' },
  @{ key = 'zhlz'; name = '中恒律证咨询（北京）事务所';     code = '31110000E00019437K'; internal = $false; contact = '马晓彤'; phone = '010-65021799' },
  @{ key = 'jcwl'; name = '锦程物流供应链有限公司';         code = '91210200MA0Y3F5A9Q'; internal = $false; contact = '刘天宇'; phone = '0411-82670033' },
  @{ key = 'tgjm'; name = '天工精密仪器有限公司';           code = '91330400MA28E9WY6J'; internal = $false; contact = '钱敏华'; phone = '0573-82078855' },
  @{ key = 'lzwy'; name = '绿洲物业服务集团';               code = '91330100MA27X1KQ4L'; internal = $false; contact = '许丹丹'; phone = '0571-86901234' },
  @{ key = 'xjrj'; name = '迅捷软件开发有限公司';           code = '91510100MA6CFN8J1T'; internal = $false; contact = '罗一鸣'; phone = '028-85321166' },
  @{ key = 'hxrl'; name = '恒信人力资源服务有限公司';       code = '91420100MA4K7B3E5W'; internal = $false; contact = '田甜';   phone = '027-87556699' },
  @{ key = 'zysj'; name = '卓远设计咨询工作室';             code = '92330106MA2KE8QW3F'; internal = $false; contact = '韩雪莹'; phone = '0571-87304455' }
)
$PartyIds = @{}
foreach ($p in $PartySpecs) {
  $r = Api $admin POST '/clm/party/create' @{ partyType = 1; name = $p.name; unifiedCreditCode = $p.code; internalFlag = $p.internal; contactName = $p.contact; contactPhone = $p.phone; status = 0 }
  if ($r.code -ne 0) { Step $false "party $($p.name) (msg=$($r.msg))"; throw "party create failed" }
  $PartyIds[$p.key] = $r.data
  $script:CreatedPartyIds += $r.data
}
Step ($PartyIds.Count -eq 12) "12 parties created"

# ------------------------------------------------------- 4. contracts (§3.5)
# states: draft | running_node1 (waiting 法务 yudao) | running_node2 (waiting 负责人 admin)
#         rejected | approved (awaiting archive) | signed (archived with scan file)
Write-Host "== step 4: contracts across lifecycle states"
$ContractSpecs = @(
  @{ key = 'sv-purchase'; state = 'signed';  owner = 'admin'; type = 'purchase';     title = '2025年度服务器及存储设备采购合同';      amount = 2860000; our = 'lx';   cp = 'qmzz'; doc = '采购合同范本.docx';
     eff = '2025-11-01'; exp = '2026-10-31'; sign = '2025-10-28'; custom = @{ deliveryDate = '2025-12-15'; acceptCriteria = '到货后10个工作日内完成上架加电与压力测试，双方签署验收单。'; warrantyMonths = 36 } },
  @{ key = 'sensor-sales'; state = 'signed'; owner = 'admin'; type = 'sales';        title = '华东区工业传感器年度销售框架合同';      amount = 4120000; our = 'lx';   cp = 'hnyc'; doc = '销售合同范本.docx';
     eff = '2026-01-01'; exp = '2026-12-31'; sign = '2025-12-20'; custom = @{ paymentDays = 60; freightIncluded = $true } },
  @{ key = 'office-lease'; state = 'signed'; owner = 'admin'; type = 'lease';        title = '杭州研发中心办公场地租赁合同';          amount = 960000;  our = 'lx';   cp = 'lzwy'; doc = '房屋租赁合同范本.docx';
     eff = '2026-03-01'; exp = '2027-02-28'; sign = '2026-02-20'; custom = @{ leaseMonths = 12; depositAmount = 160000 } },
  @{ key = 'dataplat';    state = 'signed';  owner = 'yudao'; type = 'tech-service'; title = '数据中台建设技术服务合同';              amount = 1680000; our = 'lxri'; cp = 'xjrj'; doc = '技术服务合同范本.docx';
     eff = '2026-04-01'; exp = '2026-12-31'; sign = '2026-03-25'; custom = @{ servicePeriod = '2026年4月至2026年12月'; milestones = 'M1 需求确认；M2 数据接入上线；M3 指标服务验收。' } },
  @{ key = 'maint';       state = 'signed';  owner = 'admin'; type = 'tech-service'; title = '精密检测设备年度维保服务合同';          amount = 580000;  our = 'lx';   cp = 'tgjm'; doc = '设备维保合同范本.docx';
     eff = '2026-05-01'; exp = '2027-04-30'; sign = '2026-04-22'; custom = @{ servicePeriod = '2026年5月至2027年4月'; milestones = '按季度巡检并出具报告，年度考核合格。' } },
  @{ key = 'cs-outsrc';   state = 'signed';  owner = 'admin'; type = 'outsourcing';  title = '客服中心业务劳务外包合同';              amount = 1320000; our = 'lx';   cp = 'hxrl'; doc = '劳务外包合同范本.docx';
     eff = '2026-06-01'; exp = '2027-05-31'; sign = '2026-05-18'; custom = @{ settlementMethod = '按月结算，次月15日前支付' } },
  @{ key = 'park-nda';    state = 'approved'; owner = 'admin'; type = 'nda';         title = '智慧园区项目战略合作保密协议';          amount = 30000;   our = 'lx';   cp = 'lwjs'; doc = '保密协议范本.docx';
     eff = '2026-08-01'; exp = '2029-07-31'; custom = @{ confidentialYears = 3 } },
  @{ key = 'office-buy';  state = 'approved'; owner = 'admin'; type = 'purchase';    title = '2026年度办公设备采购合同';              amount = 876000;  our = 'lx';   cp = 'qmzz'; doc = '采购合同范本.docx';
     eff = '2026-09-01'; exp = '2027-08-31'; custom = @{ deliveryDate = '2026-09-30'; acceptCriteria = '开箱验机合格并完成资产登记。'; warrantyMonths = 24 } },
  @{ key = 'vision-dev';  state = 'approved'; owner = 'yudao'; type = 'tech-service'; title = '视觉检测算法定制开发技术服务合同';     amount = 2360000; our = 'lxri'; cp = 'hnyc'; doc = '技术服务合同范本.docx';
     eff = '2026-09-01'; exp = '2027-06-30'; custom = @{ servicePeriod = '2026年9月至2027年6月'; milestones = 'M1 样本标注；M2 模型交付；M3 产线试运行验收。' } },
  @{ key = 'sw-sales';    state = 'running_node1'; owner = 'admin'; type = 'sales';  title = '西南区智能终端销售合同';                amount = 3450000; our = 'lx';   cp = 'lwjs'; doc = '销售合同范本.docx';
     eff = '2026-10-01'; exp = '2027-09-30'; custom = @{ paymentDays = 45; freightIncluded = $false } },
  @{ key = 'wh-lease';    state = 'running_node2'; owner = 'admin'; type = 'lease';  title = '厂区仓储用房租赁合同';                  amount = 420000;  our = 'lx';   cp = 'lzwy'; doc = '房屋租赁合同范本.docx';
     eff = '2026-10-01'; exp = '2028-09-30'; custom = @{ leaseMonths = 24; depositAmount = 70000 } },
  @{ key = 'parts-supp';  state = 'running_node2'; owner = 'admin'; type = 'purchase'; title = '核心零部件供货补充协议';              amount = 1580000; our = 'lx';   cp = 'tgjm'; doc = '供货补充协议.docx';
     eff = '2026-09-15'; exp = '2027-03-31'; custom = @{ deliveryDate = '2026-11-30'; acceptCriteria = '按增补供货清单分批抽检，抽检合格率不低于99%。'; warrantyMonths = 12 } },
  @{ key = 'line-outsrc'; state = 'rejected'; owner = 'admin'; type = 'outsourcing'; title = '生产线改造辅助劳务外包合同';            amount = 760000;  our = 'lx';   cp = 'hxrl'; doc = '劳务外包合同范本.docx';
     eff = '2026-09-01'; exp = '2027-02-28'; custom = @{ settlementMethod = '按工作量月度结算' }; rejectReason = '结算条款与预算口径不一致，请调整后重新提交。' },
  @{ key = 'rd-nda';      state = 'draft';   owner = 'admin'; type = 'nda';          title = '新产品联合研发保密协议';                amount = 50000;   our = 'lxri'; cp = 'zysj'; doc = '保密协议范本.docx';
     eff = '2026-10-01'; exp = '2031-09-30'; custom = @{ confidentialYears = 5 } },
  @{ key = 'mkt-buy';     state = 'draft';   owner = 'admin'; type = 'purchase';     title = '2026年市场推广物料采购合同';            amount = 390000;  our = 'lx';   cp = 'jcwl'; doc = $null;  # draft without main document yet
     eff = '2026-10-01'; exp = '2026-12-31'; custom = @{ deliveryDate = '2026-10-20'; acceptCriteria = '物料印刷颜色与样稿一致，数量清点无误。'; warrantyMonths = 3 } }
)

function Get-OwnerHeaders($spec) { if ($spec.owner -eq 'yudao') { return $yudao } else { return $admin } }
function Approve-Node($headers, $instanceId, $reason) {
  $todo = (Api $headers GET '/bpm/task/todo-page?pageNo=1&pageSize=100').data.list | Where-Object { $_.processInstance.id -eq $instanceId }
  if (@($todo).Count -lt 1) { throw "no todo task for instance $instanceId" }
  $r = Api $headers PUT '/bpm/task/approve' @{ id = @($todo)[0].id; reason = $reason }
  if ($r.code -ne 0) { throw "approve failed: $($r.msg)" }
}
function Get-OffsetDays($state) {
  switch ($state) {
    'signed'        { return (Get-Random -Minimum 45 -Maximum 76) }
    'approved'      { return (Get-Random -Minimum 20 -Maximum 46) }
    'rejected'      { return (Get-Random -Minimum 10 -Maximum 41) }
    'running_node1' { return (Get-Random -Minimum 3  -Maximum 21) }
    'running_node2' { return (Get-Random -Minimum 3  -Maximum 21) }
    default         { return (Get-Random -Minimum 1  -Maximum 11) }
  }
}

$ContractIds = @{}
foreach ($cs in $ContractSpecs) {
  $owner = Get-OwnerHeaders $cs
  $body = @{
    title = $cs.title; typeId = $TypeIds[$cs.type]; amount = $cs.amount; currency = 'CNY'
    effectiveDate = $cs.eff; expiryDate = $cs.exp
    description = "$($cs.title)（演示数据）"
    customData = $cs.custom
    parties = @(
      @{ partyId = $PartyIds[$cs.our]; roleCode = 'OUR_SIDE'; sort = 1 },
      @{ partyId = $PartyIds[$cs.cp]; roleCode = 'COUNTERPARTY'; sort = 2 }
    )
  }
  $r = Api $owner POST '/clm/contract/create' $body
  if ($r.code -ne 0) { Step $false "create '$($cs.title)' (msg=$($r.msg))"; throw "contract create failed" }
  $cid = $r.data
  $ContractIds[$cs.key] = $cid
  $script:CreatedContractIds += @{ id = $cid; offsetDays = (Get-OffsetDays $cs.state) }

  if ($cs.doc) {
    $up = Upload $owner '/clm/contract/document/upload' @{ contractId = $cid; roleCode = 'MAIN'; remark = '正文 v1' } (Join-Path $DocDir $cs.doc)
    if ($up.code -ne 0) { Step $false "upload main doc for '$($cs.title)' (msg=$($up.msg))"; throw "doc upload failed" }
  }

  if ($cs.state -ne 'draft') {
    $r = Api $owner POST '/clm/contract/submit' @{ id = $cid; remark = '请审批' }
    if ($r.code -ne 0) { Step $false "submit '$($cs.title)' (msg=$($r.msg))"; throw "submit failed" }
    $bindingId = $r.data
    $binding = (Api $owner GET "/clm/workflow-binding/list?contractId=$cid").data | Where-Object { $_.id -eq $bindingId }
    $inst = $binding.processInstanceId
    Start-Sleep -Milliseconds 500

    if ($cs.state -eq 'rejected') {
      $todo = (Api $yudao GET '/bpm/task/todo-page?pageNo=1&pageSize=100').data.list | Where-Object { $_.processInstance.id -eq $inst }
      if (@($todo).Count -lt 1) { Step $false "no todo to reject for '$($cs.title)'"; throw "reject failed" }
      $r = Api $yudao PUT '/bpm/task/reject' @{ id = @($todo)[0].id; reason = $cs.rejectReason }
      if ($r.code -ne 0) { Step $false "reject '$($cs.title)' (msg=$($r.msg))"; throw "reject failed" }
    }
    elseif ($cs.state -in 'running_node2', 'approved', 'signed') {
      Approve-Node $yudao $inst '法务审核通过'
      Start-Sleep -Milliseconds 500
      if ($cs.state -in 'approved', 'signed') {
        Approve-Node $admin $inst '同意'
        Start-Sleep -Seconds 1
      }
    }
    # running_node1: submitted, no approval action -> waits at 法务 (yudao)
  }

  if ($cs.state -eq 'signed') {
    # archive with a stamped-scan placeholder (re-use the contract main DOCX as scan file)
    $scan = Join-Path $DocDir $cs.doc
    $arch = Upload $owner '/clm/contract/archive' @{ contractId = $cid; signDate = $cs.sign; effectiveDate = $cs.eff; expiryDate = $cs.exp } $scan
    if ($arch.code -ne 0) { Step $false "archive '$($cs.title)' (msg=$($arch.msg))"; throw "archive failed" }
  }

  # verify final state
  $c = (Api $owner GET "/clm/contract/get?id=$cid").data
  $ok = switch ($cs.state) {
    'draft'         { $c.approvalStatus -eq 0 -and $c.lifecycleStatus -eq 1 }
    'running_node1' { $c.approvalStatus -eq 1 }
    'running_node2' { $c.approvalStatus -eq 1 }
    'rejected'      { $c.approvalStatus -eq 3 -and $c.lifecycleStatus -eq 1 }
    'approved'      { $c.approvalStatus -eq 2 -and $c.lifecycleStatus -eq 2 }
    'signed'        { $c.approvalStatus -eq 2 -and $c.lifecycleStatus -eq 3 }
  }
  Step $ok "[$($cs.state)] id=$cid $($cs.title) (approval=$($c.approvalStatus) lifecycle=$($c.lifecycleStatus))"
}

# --------------------------------------- 5. copy / renewal relations (§3.5)
Write-Host "== step 5: copy + renewal relations"
$r = Api $admin POST '/clm/contract/copy' @{ sourceContractId = $ContractIds['sensor-sales']; relationType = 'COPY' }
Step ($r.code -eq 0) "copy of 华东区工业传感器年度销售框架合同 -> id=$($r.data) (msg=$($r.msg))"
if ($r.code -eq 0) { $script:CreatedContractIds += @{ id = $r.data; offsetDays = (Get-Random -Minimum 1 -Maximum 8) } }

$r = Api $admin POST '/clm/contract/copy' @{ sourceContractId = $ContractIds['office-lease']; relationType = 'RENEWAL'; title = '杭州研发中心办公场地租赁合同（2027年度续签）' }
Step ($r.code -eq 0) "renewal of 杭州研发中心办公场地租赁合同 -> id=$($r.data) (msg=$($r.msg))"
if ($r.code -eq 0) { $script:CreatedContractIds += @{ id = $r.data; offsetDays = (Get-Random -Minimum 1 -Maximum 8) } }

# --------------------------------------------- 6. backdate timestamps (§3.6)
Write-Host "== step 6: backdate timestamps via mysql (only rows created by this run)"
$envFile = Join-Path $ClmRoot 'infra\.env'
$dbPass = ((Get-Content $envFile | Where-Object { $_ -match '^CLM_DB_PASSWORD=' } | Select-Object -First 1) -replace '^CLM_DB_PASSWORD=', '').Trim()
$dbUser = ((Get-Content $envFile | Where-Object { $_ -match '^CLM_DB_USERNAME=' } | Select-Object -First 1) -replace '^CLM_DB_USERNAME=', '').Trim()
if (-not $dbUser) { $dbUser = 'root' }
$mysqlExe = Join-Path $ClmRoot 'runtime\tools\mysql-8.0.33-winx64\bin\mysql.exe'
if (-not (Test-Path $mysqlExe)) { Step $false "mysql.exe not found at $mysqlExe"; throw "mysql missing" }

$sqlLines = New-Object System.Collections.Generic.List[string]
# types + parties were created first: push them further back than any contract (fixed 80 days)
if ($script:CreatedTypeIds.Count -gt 0) {
  $in = ($script:CreatedTypeIds -join ',')
  $sqlLines.Add("UPDATE clm_contract_type SET create_time = DATE_SUB(create_time, INTERVAL 80 DAY), update_time = DATE_SUB(update_time, INTERVAL 80 DAY) WHERE id IN ($in);")
  $sqlLines.Add("UPDATE clm_contract_type_version SET create_time = DATE_SUB(create_time, INTERVAL 80 DAY), update_time = DATE_SUB(update_time, INTERVAL 80 DAY) WHERE type_id IN ($in);")
}
if ($script:CreatedPartyIds.Count -gt 0) {
  $in = ($script:CreatedPartyIds -join ',')
  $sqlLines.Add("UPDATE clm_party SET create_time = DATE_SUB(create_time, INTERVAL 80 DAY), update_time = DATE_SUB(update_time, INTERVAL 80 DAY) WHERE id IN ($in);")
}
# per-contract: shift every row of that contract by ONE offset so relative event order is preserved
foreach ($e in $script:CreatedContractIds) {
  $cid = $e.id; $d = $e.offsetDays
  $sqlLines.Add("UPDATE clm_contract SET create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE id = $cid;")
  $sqlLines.Add("UPDATE clm_contract_party SET create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE contract_id = $cid;")
  $sqlLines.Add("UPDATE clm_document SET create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE contract_id = $cid;")
  $sqlLines.Add("UPDATE clm_document_version SET create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE contract_id = $cid;")
  $sqlLines.Add("UPDATE clm_workflow_binding SET create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE contract_id = $cid;")
  $sqlLines.Add("UPDATE clm_audit_event SET occurred_at = DATE_SUB(occurred_at, INTERVAL $d DAY), create_time = DATE_SUB(create_time, INTERVAL $d DAY), update_time = DATE_SUB(update_time, INTERVAL $d DAY) WHERE contract_id = $cid;")
}
$sqlFile = Join-Path $ClmRoot 'runtime\tmp\seed-backdate.sql'
New-Item -ItemType Directory -Force (Split-Path $sqlFile) | Out-Null
[IO.File]::WriteAllLines($sqlFile, $sqlLines)   # pure ASCII content
$env:MYSQL_PWD = $dbPass
$prevEap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'   # native stderr must not throw under Stop
$out = Get-Content $sqlFile | & $mysqlExe "-u$dbUser" '--default-character-set=utf8mb4' 'ruoyi-vue-pro' 2>&1
$mysqlOk = ($LASTEXITCODE -eq 0)
$ErrorActionPreference = $prevEap
$env:MYSQL_PWD = $null
Step $mysqlOk "backdate SQL executed ($($sqlLines.Count) statements) $(if (-not $mysqlOk) { $out | Out-String })"

} catch {
  Write-Host "  FAIL  fatal: $($_.Exception.Message)" -ForegroundColor Red
  $script:Failures++
}

# ----------------------------------------------------------------- summary
Write-Host ""
Write-Host "created contract ids: $(($script:CreatedContractIds | ForEach-Object { $_.id }) -join ', ')"
if ($script:Failures -eq 0) { Write-Host "SEED COMPLETE - ALL STEPS PASSED" -ForegroundColor Green }
else { Write-Host "SEED FINISHED WITH $($script:Failures) FAILURE(S)" -ForegroundColor Red; exit 1 }
